In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Yes, there is a difference in the data type of variables list_ and array_list.

The variable list_ is a Python list, which can hold elements of different data types, including strings, integers, floats, and other objects.

On the other hand, the variable array_list is a NumPy array, which can hold elements of a single data type only. In this case, since the input list contains strings, the array_list will also have the data type of string.

In [2]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

To print the data type of each and every element of list_ and array_list, you can use a for loop to iterate over each element in the list, and then use the type() function to print the data type of that element. For the array_list, you can use the dtype attribute to get the data type of the array.

In [3]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)


for elem in list_:
    print(type(elem))

for elem in array_list:
    print(elem, type(elem))

print(array_list.dtype)


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>
<U1


Yes, there will be a difference in the data type of the elements present in both the variables, list_ and array_list after changing the data type of array_list to int.

Before the change, the list_ contains string elements, while the array_list contains numpy string elements. After changing the data type of array_list to int, the elements in array_list will be converted to integer type, while the elements in list_ will still be strings.

In [4]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_, dtype = int)

for elem in list_:
    print(type(elem))

for elem in array_list:
    print(type(elem))

print(array_list.dtype)


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
int64


In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [5]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

print(num_array.shape)

print(num_array.size)


(2, 3)
6


In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [6]:
import numpy as np

zero_array = np.zeros((3, 3))

print(zero_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [7]:
import numpy as np

identity_matrix = np.identity(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
